packages:
  - .

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild

blockExoticSubdeps: true

minimumReleaseAge: 4320
allowBuilds:
  "@swc/core": true
  core-js: true
  electron-winstaller: false
  esbuild: true
